name = "pdc-pfo"
main = "worker.js"
compatibility_date = "2026-10-01"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "pdc-pfo"
database_id = "27d9b48a-0006-49af-822c-0a91b6af5015"
migrations_dir = "migrations"

[vars]
APP_NAME = "PDC–PFO"
APP_ORIGIN = "https://pdc-pfo.pdcpfo.workers.dev"
SETUP_ADMIN_EMAIL = "admin@contoh.com"
